### ISSUE TITLE
where are the scripts to analyze?

### ISSUE THREAD

**Issue by DeoLeung** [tianon/docker-postgres-upgrade#11]
I got these messages after upgraded from 10 to 11
```bash
Optimizer statistics are not transferred by pg_upgrade so,
once you start the new server, consider running:
    ./analyze_new_cluster.sh

Running this script will delete the old cluster's data files:
    ./delete_old_cluster.sh
```

but how can I find these scripts?

**Comment by DeoLeung** [comment]
I kept the container after upgrade, the `analyze_new_cluster.sh` will be written to work directory which is not mapped to local disk.

anyway it doesn't matter, we could manually run it using `vacuumdb` command

since the message is printed at the end of the upgrade, would be confusing for newbie like me doing the upgrade for the first time :)

**Comment by gregblass** [comment]
For me on Mac OS using homebrew, my postgres install was located at /usr/local/var/postgres, and this script was located at /usr/local/var/log. Confusing as hell!
