### ISSUE TITLE
Need help with upgrade, could not open version file.

### ISSUE THREAD

**Issue by ghost** [tianon/docker-postgres-upgrade#22]
DELETE IT

**Comment by johnnygiter** [comment]
Assuming I have container named: postgres with linked database folder to host: /mnt/11
How to make upgrade from 11 to 12?

**Comment by johnnygiter** [comment]
I think I managed with directories now getting, 

> connection to database failed: FATAL:  role "postgres" does not exist

How to manage connection as different role/user?

> could not connect to source postmaster started with the command:
> "/usr/lib/postgresql/11/bin/pg_ctl" -w -l "pg_upgrade_server.log" -D "/var/lib/postgresql/11/data" -o "-p 50432 -b  -c listen_addresses='' -c unix_socket_permissions=0700 -c unix_socket_directories='/var/lib/postgresql'" start
> Failure, exiting
