### ISSUE TITLE
"exec format error" when upgrading to Postgres 11 on ARM

### ISSUE THREAD

**Issue by madrumo** [tianon/docker-postgres-upgrade#28]
Hello,
I'm currently trying to update to postgres from 10 to 11 (necessary to update my funkwhale instance, for background) on an Raspberry Pi 4 (so with an arm architecture) as stated here : https://dev.funkwhale.audio/funkwhale/funkwhale/-/releases (docker all-in-one situation)

More precisely, I tried this :

docker run --rm 
    -v $(pwd)/data:/var/lib/postgresql/10/data 
    -v $(pwd)/upgraded-postgresql:/var/lib/postgresql/11/data 
    -e PGUSER=funkwhale 
    -e POSTGRES_INITDB_ARGS="-U funkwhale --locale C --encoding UTF8" 
    tianon/postgres-upgrade:10-to-1

to download and install postgres 11. What I obtained, after the download was complete :

Status: Downloaded newer image for tianon/postgres-upgrade:10-to-11
standard_init_linux.go:211: exec user process caused "exec format error" 

I presume that the problem is linked to the fact that it's an arm architecture, and that the image used was not build for arm. Is there a way to build myself the image for arm ? Or do I have to upgrade another way ?
I precise that I'm not really used to the utilisation of postgres and docker, so maybe I miss an obvious solution.

Thank you for your help

**Comment by SuperSandro2000** [comment]
You can try building the Dockerfile on arm and see how this goes.

**Comment by tianon** [comment]
Yep, my builder for this doesn't support any ARM variants, so you'll have to do so yourself, but in theory, it should Just Work by doing something like:

```console
$ docker build -t tianon/postgres-upgrade:10-to-11 'https://github.com/tianon/docker-postgres-upgrade.git#:10-to-11'
```

**Comment by madrumo** [comment]
Thanks for your help.  This procedure doesn't seem to work, as I obtained this result 👍 

Step 3/12 : RUN apt-get update && apt-get install -y --no-install-recommends            pos         tgresql-10=10.12-2.pgdg90+1     && rm -rf /var/lib/apt/lists/*
 ---> Running in 9321365b8b9e
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:2 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease [51.4 kB]
Get:3 http://security.debian.org/debian-security stretch/updates/main armhf Packages [499 k         B]
Get:4 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main Sources [62.1 kB]
Ign:5 http://deb.debian.org/debian stretch InRelease
Get:6 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:7 http://deb.debian.org/debian stretch-backports InRelease [91.8 kB]
Get:8 http://deb.debian.org/debian stretch Release [118 kB]
Get:9 http://deb.debian.org/debian stretch Release.gpg [2,410 B]
Get:10 http://deb.debian.org/debian stretch-updates/main armhf Packages [27.9 kB]
Get:11 http://deb.debian.org/debian stretch-backports/main armhf Packages [599 kB]
Get:12 http://deb.debian.org/debian stretch/main armhf Packages [6,912 kB]
Fetched 8,548 kB in 9s (923 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package postgresql-10
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends      p         ostgresql-10=10.12-2.pgdg90+1   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1         00

So I checked and neither debian default  apt repositories (for stretch and buster) nor the postgres apt repository for debian are including a postgres 10 package for ARM architectures.

I'm currently searching an apt repository in which it is included to add it to the source list, if I found one I think that would resolve the issue.

**Comment by tianon** [comment]
Ah, that's because the repo at http://apt.postgresql.org/pub/repos/apt/
does not support 32bit ARM -- I'd suggest (since you're on a Raspberry Pi
4) that you upgrade to a 64bit ARM distro instead.
