### ISSUE TITLE
10-to12: connection to database failed: could not connect to server: No such file or directory

### ISSUE THREAD

**Issue by adacaccia** [tianon/docker-postgres-upgrade#31]
Directory structure under /mnt/ocfs2/timescaledb:
`find /mnt/ocfs2/timescaledb/ -mindepth 2 -maxdepth 2`
`/mnt/ocfs2/timescaledb/10/data`
`/mnt/ocfs2/timescaledb/12/data`

Command run:
`docker run --rm -v /mnt/ocfs2/timescaledb:/var/lib/postgresql tianon/postgres-upgrade:10-to-12 --check -O "-c timescaledb.restoring='on'"`

Results in following output:
> Performing Consistency Checks on Old Live Server
> ------------------------------------------------
> Checking cluster versions                                   ok
> connection to database failed: could not connect to server: No such file or directory
> 	Is the server running locally and accepting
> 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
> Failure, exiting

It is just impossible to get to a Unix socket in another running container!
Moreover, the 10-to-12 image downloads and installs the 10 version package, so in theory could run it locally; this would lead to:

- no need to keep the OLD running
- ability to reach the OLD db via the Unix socket.

**Comment by yosifkit** [comment]
I would guess that `--check` doesn't start the temporary servers that just `pg_upgrade` does when actually doing the upgrade, so it likely doesn't work in a container (but maybe [`PGHOST`](https://www.postgresql.org/docs/9.1/libpq-envars.html) to your running container would make it work).

**Comment by jicki** [comment]
pls  How to solve this problem.

9.6 to 12

```
connection to database failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/lib/postgresql/.s.PGSQL.50432"?
```

**Comment by cobolbaby** [comment]
@jicki How to check the `pg_upgrade_server.log` when the pg_upgrade container exists?

I meet the same question. But I have not found a way to check the log.

**Comment by theAkito** [comment]
> I'd like to know how to check the `pg_upgrade_server.log` after the pg_upgrade container exit?

You could, for example, put it into a host volume.
