### ISSUE TITLE
Is there a reason to remove upgrade ability for older versions?

### ISSUE THREAD

**Issue by KoenDG** [tianon/docker-postgres-upgrade#96]
So, this is not an accusation or criticism or anything like that, it might come across as such so apologies in advance.

My question here is wondering about the reason to drop old update images, like for instance 11 to 16.

While true that 11 is EOL, it is a version that existed at the same time as 16. There is overlap there.

It could well be that you're saying "If it's EOL I'm not going to bother looking into it", an argument of where you spend your time, fair enough.

But if the argument is more: "not developed is not supported", I would argue to leave 11->16 in there, because they existed at the same time and were both supported during that interval. Same for other versions that existed and were receiving development at the same time.

But that's just my opinion, I'm interested in reading your reply.

EDIT: The pg_upgrade documentation mentions: https://www.postgresql.org/docs/current/pgupgrade.html

> pg_upgrade supports upgrades from 9.2.X and later to the current major release of PostgreSQL, including snapshot and beta releases.

So, the postgres documentation states that this is the range of versions that should be supported(as in, the documentation guarantees it's technically possible). All the way from 9.2 through to the current latest.

**Comment by tianon** [comment]
Once they hit EOL, building images of them successfully gets harder over time (so it's more of the first).

**Comment by KoenDG** [comment]
Oh right, the images themselves still have to be built.
